/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.space.gradebook.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.training.space.gradebook.model.Submission;
import com.liferay.training.space.gradebook.model.SubmissionModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Submission service. Represents a row in the &quot;Gradebook_Submission&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SubmissionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubmissionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubmissionImpl
 * @generated
 */
@JSON(strict = true)
public class SubmissionModelImpl
	extends BaseModelImpl<Submission> implements SubmissionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a submission model instance should use the <code>Submission</code> interface instead.
	 */
	public static final String TABLE_NAME = "Gradebook_Submission";

	public static final Object[][] TABLE_COLUMNS = {
		{"submissionId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"assignmentId", Types.BIGINT},
		{"studentId", Types.BIGINT}, {"submitDate", Types.TIMESTAMP},
		{"comment_", Types.VARCHAR}, {"grade", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("submissionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("assignmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("studentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("submitDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("comment_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("grade", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Gradebook_Submission (submissionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,assignmentId LONG,studentId LONG,submitDate DATE null,comment_ STRING null,grade INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table Gradebook_Submission";

	public static final String ORDER_BY_JPQL =
		" ORDER BY submission.submissionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Gradebook_Submission.submissionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSIGNMENTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STUDENTID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBMISSIONID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.training.space.gradebook.service.util.PropsUtil.get(
			"lock.expiration.time.com.liferay.training.space.gradebook.model.Submission"));

	public SubmissionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _submissionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSubmissionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _submissionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Submission.class;
	}

	@Override
	public String getModelClassName() {
		return Submission.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Submission, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Submission, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Submission, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Submission)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Submission, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Submission, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Submission)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Submission, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Submission, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Submission, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Submission, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Submission, Object>>();

			attributeGetterFunctions.put(
				"submissionId", Submission::getSubmissionId);
			attributeGetterFunctions.put("groupId", Submission::getGroupId);
			attributeGetterFunctions.put("companyId", Submission::getCompanyId);
			attributeGetterFunctions.put("userId", Submission::getUserId);
			attributeGetterFunctions.put("userName", Submission::getUserName);
			attributeGetterFunctions.put(
				"createDate", Submission::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Submission::getModifiedDate);
			attributeGetterFunctions.put(
				"assignmentId", Submission::getAssignmentId);
			attributeGetterFunctions.put("studentId", Submission::getStudentId);
			attributeGetterFunctions.put(
				"submitDate", Submission::getSubmitDate);
			attributeGetterFunctions.put("comment", Submission::getComment);
			attributeGetterFunctions.put("grade", Submission::getGrade);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Submission, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Submission, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Submission, ?>>();

			attributeSetterBiConsumers.put(
				"submissionId",
				(BiConsumer<Submission, Long>)Submission::setSubmissionId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Submission, Long>)Submission::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Submission, Long>)Submission::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Submission, Long>)Submission::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Submission, String>)Submission::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Submission, Date>)Submission::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Submission, Date>)Submission::setModifiedDate);
			attributeSetterBiConsumers.put(
				"assignmentId",
				(BiConsumer<Submission, Long>)Submission::setAssignmentId);
			attributeSetterBiConsumers.put(
				"studentId",
				(BiConsumer<Submission, Long>)Submission::setStudentId);
			attributeSetterBiConsumers.put(
				"submitDate",
				(BiConsumer<Submission, Date>)Submission::setSubmitDate);
			attributeSetterBiConsumers.put(
				"comment",
				(BiConsumer<Submission, String>)Submission::setComment);
			attributeSetterBiConsumers.put(
				"grade", (BiConsumer<Submission, Integer>)Submission::setGrade);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getSubmissionId() {
		return _submissionId;
	}

	@Override
	public void setSubmissionId(long submissionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_submissionId = submissionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAssignmentId() {
		return _assignmentId;
	}

	@Override
	public void setAssignmentId(long assignmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assignmentId = assignmentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAssignmentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("assignmentId"));
	}

	@JSON
	@Override
	public long getStudentId() {
		return _studentId;
	}

	@Override
	public void setStudentId(long studentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_studentId = studentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalStudentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("studentId"));
	}

	@JSON
	@Override
	public Date getSubmitDate() {
		return _submitDate;
	}

	@Override
	public void setSubmitDate(Date submitDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_submitDate = submitDate;
	}

	@JSON
	@Override
	public String getComment() {
		if (_comment == null) {
			return "";
		}
		else {
			return _comment;
		}
	}

	@Override
	public void setComment(String comment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_comment = comment;
	}

	@JSON
	@Override
	public int getGrade() {
		return _grade;
	}

	@Override
	public void setGrade(int grade) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_grade = grade;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Submission.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Submission toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Submission>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SubmissionImpl submissionImpl = new SubmissionImpl();

		submissionImpl.setSubmissionId(getSubmissionId());
		submissionImpl.setGroupId(getGroupId());
		submissionImpl.setCompanyId(getCompanyId());
		submissionImpl.setUserId(getUserId());
		submissionImpl.setUserName(getUserName());
		submissionImpl.setCreateDate(getCreateDate());
		submissionImpl.setModifiedDate(getModifiedDate());
		submissionImpl.setAssignmentId(getAssignmentId());
		submissionImpl.setStudentId(getStudentId());
		submissionImpl.setSubmitDate(getSubmitDate());
		submissionImpl.setComment(getComment());
		submissionImpl.setGrade(getGrade());

		submissionImpl.resetOriginalValues();

		return submissionImpl;
	}

	@Override
	public Submission cloneWithOriginalValues() {
		SubmissionImpl submissionImpl = new SubmissionImpl();

		submissionImpl.setSubmissionId(
			this.<Long>getColumnOriginalValue("submissionId"));
		submissionImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		submissionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		submissionImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		submissionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		submissionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		submissionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		submissionImpl.setAssignmentId(
			this.<Long>getColumnOriginalValue("assignmentId"));
		submissionImpl.setStudentId(
			this.<Long>getColumnOriginalValue("studentId"));
		submissionImpl.setSubmitDate(
			this.<Date>getColumnOriginalValue("submitDate"));
		submissionImpl.setComment(
			this.<String>getColumnOriginalValue("comment_"));
		submissionImpl.setGrade(this.<Integer>getColumnOriginalValue("grade"));

		return submissionImpl;
	}

	@Override
	public int compareTo(Submission submission) {
		long primaryKey = submission.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Submission)) {
			return false;
		}

		Submission submission = (Submission)object;

		long primaryKey = submission.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Submission> toCacheModel() {
		SubmissionCacheModel submissionCacheModel = new SubmissionCacheModel();

		submissionCacheModel.submissionId = getSubmissionId();

		submissionCacheModel.groupId = getGroupId();

		submissionCacheModel.companyId = getCompanyId();

		submissionCacheModel.userId = getUserId();

		submissionCacheModel.userName = getUserName();

		String userName = submissionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			submissionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			submissionCacheModel.createDate = createDate.getTime();
		}
		else {
			submissionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			submissionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			submissionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		submissionCacheModel.assignmentId = getAssignmentId();

		submissionCacheModel.studentId = getStudentId();

		Date submitDate = getSubmitDate();

		if (submitDate != null) {
			submissionCacheModel.submitDate = submitDate.getTime();
		}
		else {
			submissionCacheModel.submitDate = Long.MIN_VALUE;
		}

		submissionCacheModel.comment = getComment();

		String comment = submissionCacheModel.comment;

		if ((comment != null) && (comment.length() == 0)) {
			submissionCacheModel.comment = null;
		}

		submissionCacheModel.grade = getGrade();

		return submissionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Submission, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Submission, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Submission, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Submission)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Submission>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Submission.class, ModelWrapper.class);

	}

	private long _submissionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _assignmentId;
	private long _studentId;
	private Date _submitDate;
	private String _comment;
	private int _grade;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Submission, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Submission)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("submissionId", _submissionId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("assignmentId", _assignmentId);
		_columnOriginalValues.put("studentId", _studentId);
		_columnOriginalValues.put("submitDate", _submitDate);
		_columnOriginalValues.put("comment_", _comment);
		_columnOriginalValues.put("grade", _grade);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("comment_", "comment");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("submissionId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("assignmentId", 128L);

		columnBitmasks.put("studentId", 256L);

		columnBitmasks.put("submitDate", 512L);

		columnBitmasks.put("comment_", 1024L);

		columnBitmasks.put("grade", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Submission _escapedModel;

}